### ISSUE TITLE
Issue with running app

### ISSUE THREAD

**Issue by dronchik** [smagolexandr/mongo_client_alt#7]
Здравствуйте,

В инструкции написано, что нужно просто сделать `docker-compuse up` и все магическим образом произойдет. Но ничего не происходит. Да и что дольжно произойти? :) Не понятно куда заходить, что смотреть - HTML5 клиент или консольный клиент? 

Попробовал зайти в `web/` директорию и запутить в ней встроенный веб-сервер:
```
mongo_client_alt $ php -S localhost:8000 -t web/
PHP 7.0.15 Development Server started at Mon Jun 26 22:06:23 2017
Listening on http://localhost:8000
Document root is /Users/andrew/projects/mongo_client_alt/web
Press Ctrl-C to quit.
[Mon Jun 26 22:06:28 2017] PHP Warning:  parse_ini_file(/Users/andrew/projects/mongo_client_alt/src/../config/db.ini): failed to open stream: No such file or directory in /Users/andrew/projects/mongo_client_alt/src/app.php on line 24
[Mon Jun 26 22:06:28 2017] PHP Fatal error:  Uncaught Error: Call to a member function match() on array in /Users/andrew/projects/mongo_client_alt/src/controllers.php:8
Stack trace:
#0 /Users/andrew/projects/mongo_client_alt/web/index.php(9): require()
#1 {main}
  thrown in /Users/andrew/projects/mongo_client_alt/src/controllers.php on line 8
[Mon Jun 26 22:06:28 2017] ::1:56175 [500]: / - Uncaught Error: Call to a member function match() on array in /Users/andrew/projects/mongo_client_alt/src/controllers.php:8
Stack trace:
#0 /Users/andrew/projects/mongo_client_alt/web/index.php(9): require()
#1 {main}
  thrown in /Users/andrew/projects/mongo_client_alt/src/controllers.php on line 8
[Mon Jun 26 22:06:42 2017] ::1:56176 Invalid request (Unexpected EOF)
^Cmongo_client_alt $ php -v
PHP 7.0.15 (cli) (built: Jan 22 2017 08:51:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```
Но ничего не произошло. Возможно есть консольный клиент, но его найти мне не удалось.

Просьба более четко описать в readme - на что именно смотреть и как запустить приложение.

Спасибо.

**Comment by smagolexandr** [comment]
Docker-compose, только поднимает бд монго і заливает фикстуры. Для запуска приложения нужен сервер с драйвером mongodb для php. Потом комманда composer install. Смотреть апп в web, всё верно.

**Comment by dronchik** [comment]
Я догадался за это, вместо того, чтобы прочитать инструкцию, но как видите, запускаться оно все равно не хочет. Т.е. проблема не решилась.

Пример хорошей и понятно инструкции можно посмотреть вот тут https://github.com/zendframework/ZendSkeletonApplication. 

Просьба перепроверить все и обновить readme так, чтобы было понятно, как запустить и настроить приложение.

**Comment by smagolexandr** [comment]
Readme обновлён. Ваша проблема была связана с отсутствием файла настройки подключения к базе данных /config/db.ini Спасибо за Вопрос.

**Comment by dronchik** [comment]
Ура, завелось! :) Спасибо.

**Comment by smagolexandr** [comment]
Thank you for feedback :)
